AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway with Lambda Token Authorizer

Resources:

  HandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: lambda_function.lambda_handler
      CodeUri: ./dist/router.zip
      Layers:
        - !Ref CreateImagesFromPdfRequirements

  CreateImagesFromPdfRequirements:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      ContentUri: ./dist/poppler-utils.zip
      CompatibleRuntimes: # optional
        - python3.7