AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to convert pdf to images

Resources:

  HandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: lambda_function.lambda_handler
      MemorySize: 512
      Timeout: 5
      CodeUri: ./dist/lambda-function.zip
      Description: Converts pdf files to images, transforms and saves to an S3 bucket
      Layers:
        - !Ref CreateImagesFromPdfRequirements

  CreateImagesFromPdfRequirements:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      ContentUri: ./dist/pdf2image-requirements.zip
      CompatibleRuntimes: # optional
        - python3.7